[package]
name = "django-template-transpiler"
version = "0.1.0"
edition = "2024"

[lib]
name = "django_template_transpiler"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.0", features = ["num-bigint"] }
regex = "1.11.2"
oxc = { version = "0.98.0", features = ["full"] }
dtl-lexer = { git = "https://github.com/LilyFirefly/django-rusty-templates", rev = "c0a5c0fc66ce7bf3b0ae21cf31b57a20bfee5f5e" }
num-bigint = "0.4.6"
